# Generated by Django 5.1.1 on 2024-11-02 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0003_visit_visitors_alter_visit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 2, 12, 22, 59, 967733)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visitors',
            field=models.IntegerField(default=0),
        ),
    ]
