# Generated by Django 5.1.1 on 2024-11-03 20:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0006_remove_visit_events_alter_visit_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 20, 48, 36, 709114)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='user',
            field=models.ForeignKey(default='userlogin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
