# Generated by Django 5.1.1 on 2024-12-17 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0011_alter_visit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 15, 45, 40, 816833)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visitors',
            field=models.IntegerField(null=True),
        ),
    ]
