# Generated by Django 5.1.1 on 2024-10-21 21:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=16)),
                ('img_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'events',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='draft', max_length=30)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 10, 21, 21, 55, 59, 370381))),
                ('formed_at', models.DateTimeField(null=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('group', models.CharField(max_length=16)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_id', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visits',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EventVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_app.event')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_app.visit')),
            ],
            options={
                'db_table': 'events_visits',
                'managed': True,
            },
        ),
    ]
