# Generated by Django 5.1.1 on 2024-10-30 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 30, 14, 2, 25, 990920)),
        ),
    ]
