# Generated by Django 5.1.1 on 2024-11-02 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0002_alter_event_img_url_alter_visit_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visitors',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 2, 12, 17, 24, 320411)),
        ),
    ]
