# Generated by Django 5.1.1 on 2024-11-03 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0005_visit_events_alter_visit_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='events',
        ),
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 20, 38, 56, 885124)),
        ),
    ]
