# Generated by Django 5.1.1 on 2024-11-03 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0007_alter_visit_created_at_alter_visit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 20, 50, 32, 382961)),
        ),
    ]
