# Generated by Django 5.1.1 on 2024-10-01 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0002_alter_visit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventvisit',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 1, 17, 46, 8, 479663)),
        ),
    ]
