# Generated by Django 5.1.1 on 2024-10-02 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0003_alter_eventvisit_date_alter_visit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 2, 10, 2, 47, 39054)),
        ),
    ]
