# Generated by Django 5.1.1 on 2024-10-02 10:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0004_alter_visit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventvisit',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_app.visit'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 2, 10, 3, 41, 835973)),
        ),
    ]
