# Generated by Django 5.1.1 on 2024-10-02 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0007_alter_eventvisit_event_alter_eventvisit_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 2, 12, 50, 24, 513190)),
        ),
    ]
